Works and about section
mertkantaroglu/Setup-and-mobile-first pull request #2
Opened 2022-12-06 19:22 UTC by mertkantaroglu

Hello,

I created works pages and about myself pages in this branch. I tried to make them as similar as I can to the original document.

However, on the about myself page, I could not solve the issues with the dev tool logos and their names. Please help me solve this issue.

Thanks,

2022-12-06 19:25 UTC, vickymarz requested changes
Hi @mertkantaroglu, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that has a failed linter check. Kindly fix your linter errors and submit again 👍🏽 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-06 20:29 UTC, emmiiorji requested changes
Hi @mertkantaroglu, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![A little bit more](https://user-images.githubusercontent.com/20554583/206012986-996f3817-a0bb-4103-acf4-72c95e9ef4d7.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adhered to GitHub flow


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 20:29 UTC, emmiiorji commented on styles.css
> +  padding-left: 10px;
Your design looks great. Kindly modify the list of languages to match the design template. The icons are in horizontal alignment with the names which have a background as shown in the illustration.

Your design:
![image](https://user-images.githubusercontent.com/20554583/206013468-cfa54b02-a50e-4968-824e-2b7c7bcdc9c5.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/206012721-c1cfabd6-9b50-4905-84d4-27121876d23d.png)

2022-12-06 20:29 UTC, emmiiorji commented on styles.css
> +}
Kindly remove unused pieces of code in order to have a more concise code base.

2022-12-06 20:29 UTC, emmiiorji commented on index.html
> +          </div>
Considering that these technology listings are not buttons but a list, I recommend that you use `li` tags for each of the items and change the div tag to `ul` to enclose the `li` tags.

Remember to adjust this for each of the projects.

2022-12-06 20:29 UTC, emmiiorji commented on index.html
> +          </ul>
Kindly include the bullets for the stack and year details of the project as shown on the design.

Your design:
![image](https://user-images.githubusercontent.com/20554583/206015425-6c729388-9f98-478a-87dc-14b62b7a60b6.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/206015458-493502a8-1cdf-4473-88c1-6d7e300e6a86.png)

2022-12-07 12:22 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @mertkantaroglu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

_**Kindly check an optional comment I left under the review and work on it please**_ :pray: 

## Highlights

-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/933d15a5d5acd62a4c99c1e2b391cacfbfe61154e349c4af39c9a99d8d10caab/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f3236444f6f4477644e474b416736554b492f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [OPTIONAL] Kindly consider adding downward and forward arrows to your design under language section. Please take a look. :point_down: 

### Your Design
![your-design](https://user-images.githubusercontent.com/26597432/206177941-7facd5e3-1682-4036-baaf-20d55292cbe2.png)


### Figma Design 
![figma-design](https://user-images.githubusercontent.com/26597432/206177967-96d048e2-90ef-4ea9-9a85-648daecebebf.png)

2022-12-07 12:48 UTC, merged